# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 954ab0deee642ab3f66ccfb43ade751a7fdbc793ac5a84c14d1849ba6c59ae88965290e272407a52c777756aea77bdd5df6832817d53af9e7ca7b7d2d3433030

test:
  secret_key_base: 4d3da5fef3c72d699739713858eda33b61d390e47cc2d6eb1bf746a3a94273a2655a808c9180819e3cd732d61446682ef4ab9aa0bca8c457edfe6ad8bb348ac6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
